### ISSUE TITLE
Password field inputs are shown as regular inputs in Active Admin

### ISSUE THREAD

**Issue by arogachev** [justinfrench/formtastic#1187] opened 2016-01-22 11:26 UTC
Initially I described problem here https://github.com/activeadmin/activeadmin/issues/4280 and thought that it was Active Admin problem.

I'm using Rails `5.0.0.beta1`, My `Gemfile` contents:

```ruby
gem 'activeadmin', github: 'activeadmin/activeadmin', branch: 'rails-5-rspec'
```
I tried to update to latest commit of Formtastic on master branch, that didn't help:

```ruby
gem 'formtastic', github: 'justinfrench/formtastic', branch: 'master'
```

For example, this line from [this file](https://github.com/activeadmin/activeadmin/blob/master/app/views/active_admin/devise/sessions/new.html.erb):

```ruby
f.input :password, label: t('active_admin.devise.password.title')
```
generates the following HTML:

```html
<input type="text" name="user[password]" id="user_password" maxlength="72">
```

So there is no `type="password"`.

**Comment by mikz** [comment] 2016-01-22 11:29
@arogachev does this happen for all the fields or just devise ?
This might be devise problem. https://github.com/plataformatec/devise/issues/3880

**Comment by arogachev** [comment] 2016-01-22 11:47
@mikz Thanks for fast reply. If i write something like this inside resource page:

```ruby
form multipart: true do |f|
  f.inputs do
    f.input :password, as: :password
  end
end
```

input is shown correctly.

I can't fully understand magic behind:

f.input :password, label: t('active_admin.devise.password.title')

Here the type is not explicitly specified, so password is rendered by name `password`?

**Comment by mikz** [comment] 2016-01-22 13:52
So the change that broke this is https://github.com/jtomaszewski/formtastic/commit/79b86c5ee0becb1cd2a795e3883c5bc319caaf83
For devise inputs, the column has no type, so we just default to string. However, we could default the type to string and check for the method name. Will fix this asap.

**Comment by mikz** [comment] 2016-01-22 15:06
@arogachev could you either provide sample project, or try to debug [the code in question](https://github.com/jtomaszewski/formtastic/blob/88f28a0bc2cdea61347b5f773ce058d68ce2fc4f/lib/formtastic/helpers/input_helper.rb#L257-L299)?

I see that it [should return `:password`](https://github.com/jtomaszewski/formtastic/blob/88f28a0bc2cdea61347b5f773ce058d68ce2fc4f/lib/formtastic/helpers/input_helper.rb#L296 even if the column type is nil) (devise case).

Also, I pushed an experimental branch enabling the new Attribute API https://github.com/justinfrench/formtastic/pull/1188.

And last, but not least. Pushed example app https://github.com/mikz/rails-5-formtastic-example that works for me. User password and password_digest correctly show as password input.

**Comment by mikz** [comment] 2016-01-24 13:19
@arogachev I can't reproduce this with rails 5. So I'd probably blame Devise for doing something bad. 
I'm going to close this as can't reproduce. Feel free to create a PR on https://github.com/mikz/rails-5-formtastic-example  that reproduces the issue.

**Comment by arogachev** [comment] 2016-01-25 03:06
@mikz So if attribute name is password and type is not explicitly specified, Forttastic guesses that it has password type, right?

**Comment by mikz** [comment] 2016-01-25 10:05
@arogachev yes, it matches the method name for `/password/` even when the type is unknown.

**Comment by arogachev** [comment] 2016-01-28 11:54
@mikz I just tested, in separate resource page this works fine:

```ruby
form multipart: true do |f|
  f.inputs do
    f.input :password, as: :password
  end
end
```
So turns out this is Devise problem, I left the comment here https://github.com/plataformatec/devise/issues/3880.

**Comment by mikz** [comment] 2016-01-28 12:20
@arogachev thanks ! Closing this then. Reopen it if something is needed from formtastic.

**Closed by mikz** 2016-01-28 12:20 UTC
